{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCallbackURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oauth2\/oauth2error\/invalidcallbackurl(url:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error\/invalidCallbackURL(URL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The callback returned doesn’t contain the expected parameters."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCallbackURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"title":"OAuth2Error.invalidCallbackURL(URL:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6OAuth20A5ErrorO18invalidCallbackURLyAC10Foundation0E0V_tcACmF","modules":[{"name":"OAuth2"}]},"hierarchy":{"paths":[["doc:\/\/OAuth2\/documentation\/OAuth2","doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error"]]},"references":{"doc://OAuth2/documentation/OAuth2":{"role":"collection","title":"OAuth2","abstract":[{"type":"text","text":"An OAuth2 client to authenticate your app with a service provider."}],"identifier":"doc:\/\/OAuth2\/documentation\/OAuth2","kind":"symbol","type":"topic","url":"\/documentation\/oauth2"},"doc://OAuth2/documentation/OAuth2/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[{"type":"text","text":"Errors thrown by the OAuth2 client."}],"identifier":"doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/oauth2\/oauth2error"},"doc://OAuth2/documentation/OAuth2/OAuth2Error/invalidCallbackURL(URL:)":{"role":"symbol","title":"OAuth2Error.invalidCallbackURL(URL:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCallbackURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The callback returned doesn’t contain the expected parameters."}],"identifier":"doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error\/invalidCallbackURL(URL:)","kind":"symbol","type":"topic","url":"\/documentation\/oauth2\/oauth2error\/invalidcallbackurl(url:)"}}}